In [2]:
#Question 1

import numpy as np

arr = np.arange(2,50,3)

print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [5]:
#Question 2

import numpy as np

list1 = []
list2 = []

for i  in range (5):
    x = int(input("Enter the value for list1 :"))
    list1.append(x)
    
print("\n")
    
for i  in range (5):
    x = int(input("Enter the value for list2 :"))
    list2.append(x)
    
arr1 = np.array(list1)
arr2 = np.array(list2)

arr = np.concatenate((arr1,arr2))
print("\nConcatenated array is :",arr)

sorted_arr = np.sort(arr)
print("\nFinal Sorted array is :",sorted_arr)

Enter the value for list1 :23
Enter the value for list1 :24
Enter the value for list1 :96
Enter the value for list1 :12
Enter the value for list1 :4


Enter the value for list2 :85
Enter the value for list2 :24
Enter the value for list2 :75
Enter the value for list2 :6
Enter the value for list2 :1

Concatenated array is : [23 24 96 12  4 85 24 75  6  1]

Final Sorted array is : [ 1  4  6 12 23 24 24 75 85 96]


In [8]:
#Question 3

import numpy as np

arr = np.array([[1, 4, 7], [3, 6, 9], [1, 4, 7], [3, 6, 9]])

print("Dimensions in array : ",arr.ndim)

print("Size of array : ",arr.size)

Dimensions in array :  2
Size of array :  12


In [10]:
#Question 4

# importing numpy
import numpy as np

# creating a 1d array
arr = np.arange(int(input()))
print("\nShape of Array :", arr.shape) 

# converting using newaxis in row wise
row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)

# converting using newaxis in column wise
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)

20

Shape of Array : (20,)

Shape of 2d Array in row major : (1, 20)

Shape of 2d Array in column major : (20, 1)


In [13]:
#Question 5

# importing numpy
import numpy as np

# creating a array with square values
arr1 = np.square([1,2,3,4,5])
arr2 = np.square([6,7,8,9,10])

# stacking and printing the value
print("Horizontal Append :",np.hstack((arr1, arr2)))
print("Vertical Append :\n", np.vstack((arr1, arr2)))

Horizontal Append : [  1   4   9  16  25  36  49  64  81 100]
Vertical Append :
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


In [15]:
#Question6

# importing numpy
import numpy as np

# creating a array
arr_1 = np.array([1,2,3,4,4,4,5,5,8,8,6,6,3,3,7,10,10,2,2])

# getting unique charater and its count
unique, counts = np.unique(arr_1, return_counts=True)

arr = np.asarray((unique, counts)).T
print(arr)

[[ 1  1]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 5  2]
 [ 6  2]
 [ 7  1]
 [ 8  2]
 [10  2]]
